@startuml
left to right direction
Class 借书者{
 借书者ID
 姓名
 性别
 电话
 借书卡号
 身份证号
 图书限额
 已借图书数目
 芝麻信用（接口）
 queryBook()
 borrowBook()
 returnBook()
 reserveBook()
 renewBook()
}
Class 图书管理员{
 管理员ID
 姓名
 agreeBorrowBook()
 agreeReturnBook()
 fine()
}
Class 系统管理员{
 管理员ID
 姓名
 addBook()
 deleteBook()
 updateBook()
 queryBook()
 addUser()
 deleteUser()
 updateUser()
 queryUser()
}
Class 借书记录{
 记录ID
 借书日期
 应还日期
 实还日期
}
Class 逾期记录{
 逾期天数
 count()
}
Class 罚款记录{
 罚款ID
 罚款金额
 fine()
}
Class 预订记录{
 记录ID
 借书卡号
 ISBN
 预订日期
}
Class 图书书目{
 图书编号
 作者
 ISBN编号
 出版社
 出版日期
}
Class 馆藏资源{
资源名称
国际出版号
价格
简介
馆藏数量
可借数量
}
Class 资源项{
馆藏流水号
状态
}
借书者 -- 借书记录
图书管理员 "1" -up- "*"借书记录 :登记
借书记录"1" -up- "0..1"逾期记录
逾期记录"*" -- "0..1"罚款记录:使用
借书者 "*" -up- "1"系统管理员
预订记录"*" -- "1"借书者
图书管理员 "*" -- "1" 系统管理员
馆藏资源"1" -- "*"预订记录 :被预订
图书书目 -up-|> 馆藏资源
馆藏资源"1" *-- "*"资源项:拥有
@enduml