@startuml
left to right direction
借书者--->(查询个人信息)
借书者--->(查询图书信息)
借书者--->(查询借阅信息)
借书者--->(预订图书)
借书者-->(解除预订)
借书者-left-->(借书)
借书者-right-->(还书)
(还书)<.(交付罚金):<<extend>>

图书管理员--->(解除预订)
图书管理员--->(预订图书)
图书管理员--->(查询图书信息)
图书管理员-right->(还书)
图书管理员-left-->(借书)

系统管理员--right-->(维护)
系统管理员-->(查询图书信息)
(维护)-up-|>(增加书籍)
(维护)-up-|>(删除书籍)
(维护)-up-|>(更新书籍)
(维护)--|>(增加借书者)
(维护)--|>(删除借书者)
(维护)--|>(更新借书者)
@enduml